kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "web-app-serve.fullname" . }}-configmap
  labels:
    component: web-app-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
data:
  # Provided configs using env
  {{- range $name, $value := .Values.env }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
