apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "web-app-serve.fullname" . }}
  labels:
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  {{- if not (kindIs "invalid" .Values.replicaCount) }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "web-app-serve.fullname" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ template "web-app-serve.fullname" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range . }}
        {{- if kindIs "string" . }}
        - name: {{ . }}
        {{- else }}
        - name: {{ .name }}
        {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Values.container.name }}
          image: {{ include "web-app-serve.container_image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ template "web-app-serve.fullname" . }}-configmap
            {{- range .Values.envFromSecrets }}
            {{- if kindIs "string" . }}
            - secretRef:
                name: {{ . }}
            {{- else }}
            - secretRef:
                {{- toYaml . | nindent 16 }}
            {{- end }}
            {{- end }}
