{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "web-app-serve.fullname" . }}-ingress
  labels:
    app: {{ template "web-app-serve.name" . }}
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
    {{- if .Values.ingress.dockerMetadataEnabled }}
    {{- include "web-app-serve.ingress_project_labels" . | nindent 4 -}}
    {{- end }}
    {{- with .Values.ingress.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ required "ingress.ingressClassName" .Values.ingress.ingressClassName | quote }}
  rules:
    - host: {{ required "ingress.hostname" .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "web-app-serve.fullname" . }}-svc
                port:
                  number: 80

  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ required "ingress.tls.secretName" .Values.ingress.tls.secretName }}
  {{- end }}

{{- end }}
