apiVersion: v1
kind: Service
metadata:
  name: {{ template "web-app-serve.fullname" . }}-svc
  labels:
    app: {{ template "web-app-serve.fullname" . }}
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "web-app-serve.fullname" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.container.port }}
