---
# Source: web-app-serve-helm/templates/configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: test-123-configmap
  labels:
    component: web-app-deployment
    environment: prod
    release: release-name
data:
  # Provided configs using env
  APP_ENVIRONMENT: "ALPHA"
  APP_TITLE: "My APP"

---
# Source: web-app-serve-helm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-123-svc
  labels:
    app: test-123
    environment: prod
    release: release-name
spec:
  type: ClusterIP
  selector:
    app: test-123
    release: release-name
    run: release-name
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
# Source: web-app-serve-helm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-123
  labels:
    environment: prod
    release: release-name
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-123
      release: release-name
      run: release-name
  template:
    metadata:
      annotations:
        checksum/configmap: eeee0ac0acc403e4dcc92d6d9496c89bf5a7db0796901d61fb156ca529d219ee
      labels:
        app: test-123
        release: release-name
        run: release-name
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: web-app-serve
          image: ghcr.io/toggle-corp/hi/some-etl-dashboard-dev:my-very-very-very-very-long-good-good-good-feat-web-app-serve.2c59d93
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 100Mi
            requests:
              cpu: "0.5"
              memory: 100Mi
          envFrom:
            - configMapRef:
                name: test-123-configmap
            - secretRef:
                name: my-app-secrets

---
# Source: web-app-serve-helm/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-123-ingress
  labels:
    app: web-app-serve-helm
    environment: prod
    release: release-name
    web-app-serve/docker-registry: "ghcr.io"
    web-app-serve/docker-org: "toggle-corp"
    web-app-serve/docker-name: "hi/some-etl-dashboard-dev"
    web-app-serve/docker-truncated-tag: "y-very-very-very-long-good-good-good-feat-web-app-serve.2c59d93"
spec:
  ingressClassName: "nginx"
  rules:
    - host: "react.web-app.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-123-svc
                port:
                  number: 80
